### ISSUE TITLE
When the PopupViewContreller dismissed,the UITableViewController which presented it,ran reloadData() didn't work

### ISSUE THREAD

**Issue by JackTheMico** [IcaliaLabs/Presentr#72] opened 2017-02-22 08:08 UTC
**Here's my PopupViewController and how I use it in my UITableViewController.**
![popup](https://cloud.githubusercontent.com/assets/19216598/23202078/54781e30-f917-11e6-9a2b-5ade9bf83b53.png)

![popintbcontroller](https://cloud.githubusercontent.com/assets/19216598/23202058/43daf566-f917-11e6-95ea-811bf06c8c51.png)

Usually,when `DispatchQueue.main.async {
                self.tableView.reloadData()
            }` worked,the method "cellForRowAtIndexPath" would ran as the nextstep.
But when PopupViewController dismissed,the "reloadData()" ran but "cellForRowAtIndexPath" didn't react, so that the tableView cannot refresh immediately.

**Comment by danlozano** [comment] 2017-03-20 18:14
Hi! Sorry for the late response, have been really busy with work, but I'm taking this whole week to look over all the issues and PR's.

I just want to understand your problem a little bit better.

So it does work when you call
```swift
DispatchQueue.main.async { self.tableView.reloadData() }
```
But not when you call
```swift
self.tableView.reloadData()
```

Or are you trying to say that the table reloading sometimes works and sometimes doesn't?

**Comment by JackTheMico** [comment] 2017-03-21 01:10
Thanks for the response! What I'm trying to say is that after you called
`DispatchQueue.main.async { self.tableView.reloadData() }`
Then the next two methods which should be called are
`overried func tableView(_tableView:UITableView, numberOfRowsInSection section:Int)->Int {}`
And
`override func tableView(_tableView:UITableView, cellForRowAtIndexPath:IndexPath)->UITableViewCell {}`
But these two methods didn't work after you called "reloadData()" with "DispatchQueue,main,async"

**Comment by danlozano** [comment] 2017-03-22 23:38
Oh ok.

Well if you're calling reloadData on a table view and those two methods are not being called that means that the releadData is not working.

Is your delegate/data-source everything setup correctly?

Can you share your code in text-form so I can look over it maybe see what's going on.

**Comment by danlozano** [comment] 2017-03-23 01:11
There's no reason for calling it on the main queue since the Presentr delegate is called on the main queue.

**Comment by JackTheMico** [comment] 2017-03-23 01:34
# MainTableViewController.swift

```swift
import Foundation
import UIKit
import Presentr

let DLWUserDefaults = UserDefaults.standard
let SWidth = UIScreen.main.bounds.width
let SHeight = UIScreen.main.bounds.height
let topController = UIApplication.shared.keyWindow?.rootViewController
let mainS = MainTableViewController.shareInstance

class MainTableViewController:UITableViewController{
    
    static let shareInstance = MainTableViewController()
    let MainSB = UIStoryboard.init(name: "Main", bundle: nil)
    let presenter:Presentr = {
        let width = ModalSize.full
        let height = ModalSize.fluid(percentage: 0.4)
        let center = ModalCenterPosition.customOrigin(origin: CGPoint.init(x: 0, y: SHeight/9))
        let presenter = Presentr.init(presentationType: .custom(width: width, height: height, center: center))
        presenter.transitionType = TransitionType.coverVerticalWithSpring
        presenter.dismissTransitionType = TransitionType.coverVerticalFromTop
        return presenter
    }()
    
    lazy  var popupViewController: PopupViewController = {
        let popupViewController:PopupViewController = self.MainSB.instantiateViewController(withIdentifier: "Popup") as! PopupViewController
        // popupViewController.delegate = self
        popupViewController.timeResponse = {(backStr:String)->Void in
            DispatchQueue.main.async {
                self.tableView.reloadData()
            }
        }
        return popupViewController
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "baseCell") as! mineCell;
        cell.presenter = self.presenter
        cell.selfController = self
        return cell
    }
}
```

# PopupViewController.swift
```swift

import Foundation
import UIKit
import Presentr

typealias TimeReturn = (_ selectTime:String)->Void

class PopupViewController:UIViewController {
    var timeResponse:TimeReturn?
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
}

extension PopupViewController:PresentrDelegate {
    func presentrShouldDismiss(keyboardShowing: Bool) -> Bool {
        print("Dismissing View Controller")
        self.timeResponse!("123454")
        return !keyboardShowing
    }
}

```

# mineCell.swift
```swift

import Foundation
import UIKit
import Presentr

class mineCell: UITableViewCell {
    var selfController:MainTableViewController?
    var presenter:Presentr?
    @IBOutlet weak var popBtn: UIButton!
    
    
    @IBAction func popBtn_clicked(_ sender: AnyObject) {
        selfController!.customPresentViewController(selfController!.presenter, viewController: mainS.popupViewController, animated: true) {
            
        }
    }
}

```
## Podfile
```
platform:ios,'8.0'
use_frameworks!
target 'ReusableTest' do
pod 'Presentr'
end
```

**Comment by JackTheMico** [comment] 2017-03-23 01:45
![storyboard1](https://cloud.githubusercontent.com/assets/19216598/24228032/75a592ee-0fac-11e7-8b1b-a86681d3b5d6.png)
![storyboard2](https://cloud.githubusercontent.com/assets/19216598/24228056/9dad3b66-0fac-11e7-9700-5d857c0b121d.png)
That's all I got. Sorry about the project's name in 'Podfile',it was a mistake.

**Comment by danlozano** [comment] 2017-03-23 03:11
Thanks for all the info!

This looks like it's a problem with your app code, for some reason the table is not reloading.

I would have architected the app a little differently but nothing stands out as me, it should be working, it should be reloading the table.

I will close this issue since this is outside Presentr, BUT if you can/want to submit a zip file with this sample code so I can run it I might help you track down the source of your problem.

**Closed by danlozano** 2017-03-23 03:11 UTC
Labels: under-investigation

**Comment by danlozano** [comment] 2017-03-23 17:32
Checked your e-mail, fixed your problem!

- First I added log messages to each of your 3 table view methods, and realized that you callback was working, and reloadData() was calling number of sections and rows, so that was "working" as well.

- But later I realized that even though those two methods are being called, the cellForRowAtIndexPath mysteriously was not being called.

Scratched my head a little bit but ultimately realized the problem. You had a static property like so:
```swift 
static let main = MainTableViewController()
```

Which honestly is a wrong architecture solution, BUT anyways, the problem is that inside your 'mineCell' you were using the static MainTableViewController, which is a different instance than the one created by you by the interface builder. So you were calling reloadData on a different instance (of the same class) of the view controller, which was calling reloadData, but since there was nothing in view since that view controller is not in view, then cellForRowAtIndexPath is not being called.

Removed the static property, and added a couple of log messages to test everything, and it seems everything is working correctly.

Check your email!

Thanks.

**Comment by JackTheMico** [comment] 2017-03-24 01:46
I finally aware of what I did wrong, I thought the static MainTableViewController and the one created by the  
interface builder would be the same one since their addresses are exactly the same one.
But apparently, they are not the same one.
Sorry for bothering you so long , really appreciate your great help!
May happiness and success follow you wherever you go!

**Comment by danlozano** [comment] 2017-03-24 16:54
No worries!

:)
